const fs = require('fs');

const mappings = {
    'Chiáº¿n dá»‹ch': 'Chiến dịch',
    'chiáº¿n dá»‹ch': 'chiến dịch',
    'gÃ¢y quá»¹': 'gây quỹ',
    'hiá»‡n váº\xadt': 'hiện vật',
    'hiá»‡n váº\xad': 'hiện vật',
    'quyÃªn gÃ³p': 'quyên góp',
    'tuyá»ƒn': 'tuyển',
    'tÃ¬nh nguyá»‡n viÃªn': 'tình nguyện viên',
    'TÃ¬nh nguyá»‡n viÃªn': 'Tình nguyện viên',
    'PhÃ¹ há»£p': 'Phù hợp',
    'cáº§n': 'cần',
    'theo dÃµi': 'theo dõi',
    'giao dá»‹ch': 'giao dịch',
    'xÃ¡c nháº\xadn': 'xác nhận',
    'xÃ¡c nháº\xad': 'xác nhận',
    'vÃ ': 'và',
    'gá»\xadz': 'gửi',
    'gá»\xad': 'gửi',
    'há»“ sÆ¡': 'hồ sơ',
    'duyá»‡t': 'duyệt',
    'Ä‘áº§y Ä‘á»§': 'đầy đủ',
    'DÃ¹ng': 'Dùng',
    'cho cÃ¡c': 'cho các',
    'Ä‘á»£t': 'đợt',
    'tiáº¿p nháº\xadn': 'tiếp nhận',
    'tiáº¿p nháº\xad': 'tiếp nhận',
    'sÃ¡ch vá»Ÿ': 'sách vở',
    'quáº§n Ã¡o': 'quần áo',
    'thá»±c pháº©m': 'thực phẩm',
    'váº\xadt dá»¥ng': 'vật dụng',
    'váº\xad dá»¥ng': 'vật dụng',
    'ghi nháº\xadn': 'ghi nhận',
    'ghi nháº\xad': 'ghi nhận',
    'sá»‘ lÆ°á»£ng': 'số lượng',
    'thá»±c táº¿': 'thực tế',
    'vá»›i': 'với',
    'hoáº¡t Ä‘á»™ng': 'hoạt động',
    'má»Ÿ': 'mở',
    'Ä‘Äƒng kÃ½': 'đăng ký',
    'xÃ©t': 'xét',
    'danh sÃ¡ch': 'danh sách',
    'chá» ': 'chờ',
    'quáº£n lÃ½': 'quản lý',
    'Ä‘á»‹a Ä‘iá»ƒm': 'địa điểm',
    'triá»ƒn khai': 'triển khai',
    'nhiá» u': 'nhiều',
    'giai Ä‘oáº¡n': 'giai đoạn',
    'thá»±c thi': 'thực thi',
    'cÃ¡i': 'cái',
    'bá»™': 'bộ',
    'quyá»ƒn': 'quyển',
    'thÃ¹ng': 'thùng',
    'pháº§n': 'phần',
    'chiáº¿c': 'chiếc',
    'há»™p': 'hộp',
    'khÃ¡c': 'khác',
    'TÃªn': 'Tên',
    'báº¯t buá»™c': 'bắt buộc',
    'TÃ³m táº¯t': 'Tóm tắt',
    'ngáº¯n': 'ngắn',
    'khÃ´ng': 'không',
    'Ä‘Æ°á»£c': 'được',
    'vÆ°á»£t quÃ¡': 'vượt quá',
    'kÃ½ tá»±': 'ký tự',
    'MÃ´ táº£': 'Mô tả',
    'chi tiáº¿t': 'chi tiết',
    'Vui lÃ²ng': 'Vui lòng',
    'chá» n': 'chọn',
    'thá» i gian': 'thời gian',
    'báº¯t Ä‘áº§u': 'bắt đầu',
    'káº¿t thÃºc': 'kết thúc',
    'pháº£i': 'phải',
    'sau hoáº·c báº±ng': 'sau hoặc bằng',
    'áº¢nh bÃ¬a': 'Ảnh bìa',
    'Má»¥c tiÃªu': 'Mục tiêu',
    'má»¥c tiÃªu': 'mục tiêu',
    'lá»›n hÆ¡n': 'lớn hơn',
    'tÃ i khoáº£n': 'tài khoản',
    'nháº\xadn tiá» n': 'nhận tiền',
    'nháº\xad tiá» n': 'nhận tiền',
    'ngÃ¢n hÃ ng': 'ngân hàng',
    'gá»“m': 'gồm',
    'chá»¯ sá»‘': 'chữ số',
    'ngÆ°á» i': 'người',
    'nháº\xadn': 'nhận',
    'nháº\xad': 'nhận',
    'trÃªn': 'trên',
    'báº£n Ä‘á»“': 'bản đồ',
    'NgÆ°á» i': 'Người',
    'phá»¥ trÃ¡ch': 'phụ trách',
    'Sá»‘ Ä‘iá»‡n thoáº¡i': 'Số điện thoại',
    'há»£p lá»‡': 'hợp lệ',
    'Pháº£i': 'Phải',
    'nháº\xadp': 'nhập',
    'khoáº£ng': 'khoảng',
    'NgÃ y': 'Ngày',
    'cá»‘ Ä‘á»‹nh': 'cố định',
    'Ã\xadt nháº¥t': 'ít nhất',
    'má»™t': 'một',
    'ngÃ y': 'ngày',
    'Má»—i': 'Mỗi',
    'Ä‘Æ¡n vá»‹': 'đơn vị',
    'tÃ\xadnh': 'tính',
    'náº¿u': 'nếu',
    'báº\xadt': 'bật',
    'diá»…n ra': 'diễn ra',
    'cÃ´ng viá»‡c': 'công việc',
    'cáº§n lÃ m': 'cần làm',
    'yÃªu cáº§u': 'yêu cầu',
    'tham gia': 'tham gia',
    'giá»›i háº¡n': 'giới hạn',
    'káº¿ hoáº¡ch': 'kế hoạch',
    'trÆ°á»›c khi': 'trước khi',
    'Táº£i': 'Tải',
    'táº£i': 'tải',
    'thÃ nh cÃ´ng': 'thành công',
    'Ä‘Ã£': 'đã',
    'lÆ°u lÃªn': 'lưu lên',
    'há»‡ thá»‘ng': 'hệ thống',
    'tháº¥t báº¡i': 'thất bại',
    'Lá»—i': 'Lỗi',
    'KhÃ´ng': 'Không',
    'toÃ n trÆ°á» ng': 'toàn trường',
    'Chá»‰': 'Chỉ',
    'thÃ nh viÃªn': 'thành viên',
    'thuá»™c': 'thuộc',
    'cÃ¢u láº¡c bá»™': 'câu lạc bộ',
    'khoa': 'khoa',
    'má»™t sá»‘': 'một số',
    'Máº«u': 'Mẫu',
    'ThÃ´ng tin cÆ¡ báº£n': 'Thông tin cơ bản',
    'Cáº¥u hÃ¬nh': 'Cấu hình',
    'Há»“ sÆ¡': 'Hồ sơ',
    'xem láº¡i': 'xem lại',
    'BÃ¬a': 'Bìa',
    'bÃ¬a': 'bìa',
    'TÃ¬m': 'Tìm',
    'cÃ³': 'có',
    'CÃ³': 'Có',
    'nÃ y': 'này',
    'Ä‘á»ƒ': 'để',
    'cá»§a': 'của',
    'ChÆ°a': 'Chưa',
    'chÆ°a': 'chưa',
    'áº£nh': 'ảnh',
    'tiá» n': 'tiền',
    'quá»¹': 'quỹ',
    'Quá»¹': 'Quỹ',
    
    // Some more problematic characters
    'Hn cu`i': 'Hạn cuối',
    '`ng kA': 'đăng ký',
    'B_t ` u': 'Bắt đầu',
    'hot `Tng': 'hoạt động',
    'Kt thAc': 'Kết thúc',
    'MA\' t': 'Mô tả',
    'cA\'ng vic': 'công việc',
    'Danh sAch': 'Danh sách',
    'c n lA m': 'cần làm',
    'M-i dAng': 'Mỗi dòng',
    'lA  mTt': 'là một',
    '` u vic': 'đầu việc',
    'YAu c u': 'Yêu cầu',
    'Quy?n li': 'Quyền lợi',
    'KhA\'ng': 'Không',
    'b_t buTc': 'bắt buộc',
    '?<a `im': 'Địa điểm',
    'phi': 'phải',
    'cA3': 'có',
    'vA ': 'và',
    't?a `T': 'tọa độ',
    'Ch?n': 'Chọn',
    'trAn': 'trên',
    'bn `"': 'bản đồ',
    'Phm vi': 'Phạm vi',
    'tuyn': 'tuyển',
    'tAnh nguyn': 'tình nguyện',
    'viAn': 'viên',
    'Quy trAnh': 'Quy trình',
    'duyt': 'duyệt',
    'c n': 'cần',
    'Cho phAcp': 'Cho phép',
    'hA ng lot': 'hàng loạt',
    'ch?': 'chờ',
    '`n v<': 'đơn vị',
    'trong': 'trong',
    'phm vi': 'phạm vi',
    'gi>i hn': 'giới hạn',
    'B>c cu`i': 'Bước cuối',
    'H" s': 'Hồ sơ',
    'g-i': 'gửi',
    'K hoch': 'Kế hoạch',
    'lA ': 'là',
    'tr>c khi': 'trước khi',
    'D trA1': 'Dự trù',
    'cA\'ng vn': 'công văn',
    'tA1y ch?n': 'tùy chọn',
    'kinh phA-': 'kinh phí',
    'tA i liu': 'tài liệu',
    'liAn quan': 'liên quan',
    'File b  sung': 'File bổ sung',
    'CA3 th': 'Có thể',
    'ti lAn': 'tải lên',
    'nhi?u': 'nhiều',
    'b  sung': 'bổ sung',
    'nu': 'nếu',
    'ThAm': 'Thêm',
    'XA3a': 'Xóa',
    'Xem li': 'Xem lại',
    'Kim tra': 'Kiểm tra',
    'thA\'ng tin': 'thông tin',
    'chin d<ch': 'chiến dịch',
    'lu nhAp': 'lưu nháp',
    'hoc': 'hoặc',
    'nh bAa': 'ảnh bìa',
    'Cha': 'Chưa',
    'B_t ` u': 'Bắt đầu',
    'nh-p': 'nhập',
    'Mu': 'Mẫu',
    'H" s': 'Hồ sơ',
    'To': 'Tạo',
    'Khu vc': 'Khu vực',
    'qun lA': 'quản lý',
    'HoA n thin': 'Hoàn thiện',
    'lu"ng': 'luồng',
    'to': 'tạo',
    'nA y': 'này',
    'dA1ng': 'dùng',
    'tht': 'thật',
    'lu': 'lưu',
    'ch%': 'chỉ',
    '`A': 'đã',
    '` y ` ': 'đầy đủ',
    'Quay li': 'Quay lại',
    'B>c': 'Bước',
    'Cu hAnh': 'Cấu hình',
    'giai `on': 'giai đoạn',
    'GAy qu1': 'Gây quỹ',
    'QuyAn gA3p': 'Quyên góp',
    'hin vt': 'hiện vật',
    'hin v-t': 'hiện vật',
    'ngay sau khi': 'ngay sau khi',
    'tip theo': 'tiếp theo',
    'hin ti': 'hiện tại',
    'l-i': 'lỗi',
    'Lu nhAp': 'Lưu nháp',
    'G-i duyt': 'Gửi duyệt'
};

const content = fs.readFileSync('e:/SEM6/01_PBL5/02_PROJECT/BKVolunteersFrontend/src/pages/shared/campaign-create-flow.tsx', 'utf-8');

let newContent = content;
for (const [bad, good] of Object.entries(mappings)) {
    newContent = newContent.split(bad).join(good);
}

fs.writeFileSync('e:/SEM6/01_PBL5/02_PROJECT/BKVolunteersFrontend/src/pages/shared/campaign-create-flow.tsx', newContent, 'utf-8');
console.log('Fixed file via js');
